[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
streamlit = ">=0.87.0"
pandas = ">=1.2"
simplejson = ">=3.0"
python-dotenv = "^0.19.1"

[build-system]  
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

